# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

services:
  - python:latest
  - gcc:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

build dependencies:
  stage: build
  environment: 
    name: Dev
  variables: 
    TOKEN: ${TOKEN}
    OWNER_ID: ${OWNER_ID}
    PREFIX: ${PREFIX}
  script:
    - npm config set python '/usr/bin/python3'
    - npm install

app:
  stage: deploy
  environment: 
    name: Dev
  script:
    - npm run start
