# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

services:
  - python:latest
  - gcc:latest

build dependencies:
  stage: build
  environment: Dev
  variables: 
    TOKEN: ${TOKEN}
    OWNER_ID: ${OWNER_ID}
    PREFIX: ${PREFIX}
  script:
    - yarn install

app:
  stage: deploy
  environment: Dev
  script:
    - yarn run start
