#!/bin/sh
# Exit immediately if a command exits with a non-zero status.
set -e

echo "Bot Entrypoint: Starting..."

# ==============================================================================
# Generate lavaNodesConfig.js from Environment Variables
# ==============================================================================
# This uses environment variables passed into the container (e.g., from docker-compose)
# to create the configuration file needed by the bot to connect to Lavalink.
# Default values are provided using :- syntax in case the environment variables are not set.

echo "Bot Entrypoint: Generating lavaNodesConfig.js..."
cat > lavaNodesConfig.js << EOF
// Generated by entrypoint.sh at container start
const nodes = [
  {
    authorization: "${LAVALINK_PASSWORD:-your lavalink password here}",
    host: "${LAVALINK_HOST:-lavalink}",
    port: ${LAVALINK_PORT:-2333},
    id: "${LAVALINK_NODE_ID:-mainNode}",
    secure: ${LAVALINK_SECURE:-false}
  },
];

export { nodes };
EOF
echo "Bot Entrypoint: lavaNodesConfig.js generated successfully."


# ==============================================================================
# Start the Bot Application
# ==============================================================================
# The 'exec' command replaces the current shell process with the 'yarn start' process.
# This ensures that 'yarn start' becomes the main process (PID 1) in the container,
# which is important for signal handling (like stopping the container).

echo "Bot Entrypoint: Executing 'yarn start'..."
exec yarn start 