#!/bin/sh
echo "Lavalink Entrypoint: Starting..."

# ==============================================================================
# Generate application.yml from Environment Variables
# ==============================================================================
# This uses environment variables passed into the container (e.g., from docker-compose)
# to create the application.yml configuration file needed by Lavalink.

echo "Lavalink Entrypoint: Generating application.yml..."
cat > application.yml << EOF
# Generated by entrypoint.sh at container start
server:
  port: ${LAVALINK_PORT}
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    pot:
      token: ${LAVALINK_YOUTUBE_POT_TOKEN:-}
      visitorData: ${LAVALINK_YOUTUBE_POT_VISITORDATA:-}
    clients:
      - WEB
      - WEBEMBEDDED
  lavasrc:
    providers:
      - "local:%QUERY%"
      - "ytsearch:%QUERY%"
      - "scsearch:%QUERY%"
    sources:
      spotify: ${LAVALINK_SPOTIFY_ENABLED:-false}
      youtube: true
      soundcloud: true
    spotify:
      clientId: ${LAVALINK_SPOTIFY_CLIENT_ID:-}
      clientSecret: ${LAVALINK_SPOTIFY_CLIENT_SECRET:-}
      countryCode: ${LAVALINK_SPOTIFY_COUNTRY_CODE:-US}
      playlistLoadLimit: ${LAVALINK_SPOTIFY_PLAYLIST_LOAD_LIMIT:-100}
      albumLoadLimit: ${LAVALINK_SPOTIFY_ALBUM_LOAD_LIMIT:-100}
      resolveArtistsInSearch: true
      localFiles: true
lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.7.0"
      snapshot: false
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.2"
      snapshot: false
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube: true
      spotify: ${LAVALINK_SPOTIFY_ENABLED:-false}
      soundcloud: true
      local: true
    local:
      enabled: true
      directory: /app/downloads
      allowedExtensions:
        - mp3
        - wav
        - ogg
        - flac
    bufferDurationMs: 400
    frameBufferDurationMs: 1000
    youtubePlaylistLoadLimit: 100
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    search:
      enabled: true
      defaultSearchEngine: local
      fallbackSearchEngine: youtube
EOF
echo "Lavalink Entrypoint: application.yml generated successfully."


# ==============================================================================
# Start the Lavalink Server
# ==============================================================================
# The 'exec' command replaces the current shell process with the java process.
# This ensures that java becomes the main process (PID 1) in the container,
# which is important for signal handling (like stopping the container).

echo "Lavalink Entrypoint: Executing 'java -jar Lavalink.jar'..."
exec java -jar Lavalink.jar 