#!/bin/sh
echo "Lavalink Entrypoint: Starting..."

# ==============================================================================
# Generate application.yml from Environment Variables
# ==============================================================================
# This uses environment variables passed into the container (e.g., from docker-compose)
# to create the application.yml configuration file needed by Lavalink.

echo "Lavalink Entrypoint: Generating application.yml..."
cat > application.yml << EOF
# Generated by entrypoint.sh at container start
server:
  port: ${LAVALINK_PORT}
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    pot:
      token: ${LAVALINK_YOUTUBE_POT_TOKEN}
      visitorData: ${LAVALINK_YOUTUBE_POT_VISITORDATA}
    clients:
      - WEB
      - WEBEMBEDDED
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: ${LAVALINK_SPOTIFY_ENABLED}
      youtube: true
    spotify:
      clientId: ${LAVALINK_SPOTIFY_CLIENT_ID}
      clientSecret: ${LAVALINK_SPOTIFY_CLIENT_SECRET}
      countryCode: ${LAVALINK_SPOTIFY_COUNTRY_CODE}
      playlistLoadLimit: ${LAVALINK_SPOTIFY_PLAYLIST_LOAD_LIMIT}
      albumLoadLimit: ${LAVALINK_SPOTIFY_ALBUM_LOAD_LIMIT}
      resolveArtistsInSearch: true
      localFiles: false
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.2"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.4.2"
      snapshot: false
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube: false
      spotify: false
EOF
echo "Lavalink Entrypoint: application.yml generated successfully."


# ==============================================================================
# Start the Lavalink Server
# ==============================================================================
# The 'exec' command replaces the current shell process with the java process.
# This ensures that java becomes the main process (PID 1) in the container,
# which is important for signal handling (like stopping the container).

echo "Lavalink Entrypoint: Executing 'java -jar Lavalink.jar'..."
exec java -jar Lavalink.jar 